# currently broken
---
name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  repo-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: go-task/setup-task@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          rustflags: ""
      - run: task sync-crds
